# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grp_cont', models.CharField(max_length=1500)),
            ],
        ),
    ]
