# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20170628_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Grp_cont',
            new_name='grp_cont',
        ),
    ]
