# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_auto_20170628_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='grp_cont',
        ),
    ]
