# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 13:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0006_auto_20170628_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demomodel',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(default='XY'),
        ),
        migrations.AlterField(
            model_name='group',
            name='grp_cont',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='group',
            name='grp_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
