# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-22 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0011_auto_20170721_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
